# Generated by Django 4.2.3 on 2023-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='товар')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('category', models.CharField(max_length=250, verbose_name='категория')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('title',),
            },
        ),
    ]
